vich_uploader:
    db_driver: orm
    metadata:
      type: attribute

    mappings:
        poster_file:
            uri_prefix: /images/uploads/posters
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
